---
title: "World Population Flags"
output-file: "index.html"
format: 
  closeread-html:
    embed-resources: false
theme: "none"
css:
  - css/styles.css
  - css/playfair-display.css
  - css/roboto.css
include-in-header:
  - file: observable-setup.html
  - text: <link rel="icon" href="media/favicon-transparent-stacked.png" type="image/png"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
---

------------------------------------------------------------------------

::: {.cr-section layout="overlay-left"}

::: {#cr-map-world}
<div class="container">
  <div id="observablehq-map-world" class="observable-map"></div>
</div>
:::

::: {#cr-map-focus-asia}
<div class="container">
  <div id="observablehq-map_focus_asia" class="observable-map"></div>
</div>
:::

::: {#cr-map-focus-africa}
<div class="container">
  <div id="observablehq-map_focus_africa" class="observable-map"></div>
</div>
:::

::: {#cr-map-focus-americas}
<div class="container">
  <div id="observablehq-map_focus_americas" class="observable-map"></div>
</div>
:::

::: {#cr-map-focus-europe}
<div class="container">
  <div id="observablehq-map_focus_europe" class="observable-map"></div>
</div>
:::

::: {#cr-map-focus-europe-and-oceania}
<div class="container">
  <div id="observablehq-map_focus_europe_and_oceania" class="observable-map"></div>
</div>
:::


<span class="next-continent">What if we displayed the countries as circle-shaped flags and sized them proportionally by their population?</span><br><br>Welcome to this visualisation of the world's population. In this **Dorling cartogram**, each country is represented by its flag in the shape of a circle, with the size of the circle corresponding to the population of that country. This approach allows us to see relative population sizes in a visually intuitive way.<br><br>**Scroll to explore** the population flags of the world.<br><br>
[@cr-map-world]

Explore this map by scrolling to gain insight into how populations are distributed across different regions and how each country compares to others. At the end of the page, you have the chance to explore the map yourself in more detail.
[@cr-map-world]

<span class="next-continent">In 2000, there were an estimated 6.1 billion people on the planet. By 2021, that number had climbed to nearly 7.9 billion.</span><br><br>This growth has been uneven across continents, driven by various factors including fertility rates, migration, and economic development.

<span class="next-continent">**Asia** is the continent with the most people in the world.</span><br><br>Asia has grown a lot since 2000. Asia's population has grown from 3.7 billion at the turn of the millennium to **4.7 billion** by 2021, largely driven by growth in countries like India, Pakistan, and Indonesia.
[@cr-map-focus-asia]

<span class="next-continent">**India and China**, the two countries with the largest population, together make up about one-third of the world's population.</span><br><br>While China’s growth rate has slowed significantly due to its aging population and policies like the former one-child policy, India’s population continues to grow rapidly and has surpassed China's.
[@cr-map-focus-asia]{pan-to="-30%,25%" scale-by="2.2"}

The demographic story of Asia is evolving. While India's population continues to rise rapidly, countries like Japan and South Korea face declining birth rates, prompting concerns about economic sustainability. Despite these challenges, the continent remains dynamic, with expanding cities, a growing middle class, and increasing life expectancy.
[@cr-map-focus-asia]{pan-to="-28%,8%" scale-by="1.6"}

<span class="next-continent">**Africa**'s population has seen dramatic growth since 2000.</span> [@cr-map-focus-asia]{pan-to="10%,-27%" scale-by="1.8"}

In 2000, the continent had approximately 814 million inhabitants. By 2021, this number surged to around **1.4 billion**, making Africa the second most populous continent. This rapid increase is primarily due to high birth rates and improvements in healthcare that have reduced mortality rates. The population growth rate in Africa remains the highest among all continents, driven by a youthful demographic and large families.<br><br><span class="next-continent">Projections suggest that by 2050, Africa's population could double.</span>
[@cr-map-focus-africa]

<span class="next-continent">The population of the **Americas** has exhibited a consistent upward trajectory since 2000.</span> [@cr-map-focus-africa]{pan-to="40%,0%" scale-by="1.1"}

The combined population of **North and South America** increased from 841 million in 2000 to **1.04 billion** by 2021. The United States, Mexico, and Brazil are the main contributors to this growth, driven by relatively high birth rates and substantial immigration. Canada also experiences growth, albeit at a slower rate. Urbanisation is a significant trend, with many people moving to cities in search of better opportunities, leading to the expansion of urban areas and associated socio-economic challenges. Overall, the Americas display diverse demographic trends, with increasing urban populations and growing diversity shaping the region's social and economic landscapes.
[@cr-map-focus-americas]

<span class="next-continent">Meanwhile, the population dynamics in **Europe** are different to the other continents.</span> [@cr-map-focus-europe]{pan-to="10%,0%" scale-by="0.8"}

The continent has experienced relatively slow growth since 2000. The population in 2000 was about 726 million and has increased modestly to around **745 million** in 2021. Many European countries face low birth rates and aging populations, leading to demographic challenges such as labor shortages and increased healthcare demands. Some growth has been sustained through immigration. Despite these trends, Europe remains one of the least densely populated continents relative to its economic output and land area.
[@cr-map-focus-europe]{pan-to="18.5%,70%" scale-by="2.8"}

<span class="next-continent">**Oceania**, including Australia, New Zealand, and the Pacific islands, has experienced a steady population growth since 2000.</span>[@cr-map-focus-europe]{pan-to="-55%,-70%" scale-by="1.8"}

The population of the region has **increased from around 31 million to about 44 million** by 2021, driven by Australia's immigration policies and expanding economic opportunities. Similarly, New Zealand has seen consistent increases, while growth rates among smaller Pacific island nations fluctuate due to varying economic conditions and emigration trends. Across Oceania, demographic changes are shaped by a combination of natural population growth and migration, contributing to the region's evolving and diverse population landscape.
[@cr-map-focus-europe-and-oceania]{pan-to="-55%,-70%" scale-by="1.8"}

<span class="next-continent">Now explore the flags of the world by yourself.</span><br><br>Zoom in to discover the populations of smaller countries that might be less immediately visible, such as those in the Pacific Islands or the Caribbean. Hover over a flag to see the exact number of inhabitants.
[@cr-map-focus-europe-and-oceania]{pan-to="0%,0%" scale-by="0"}

:::

:::{#cr-map-world-zoomable}
<div class="container">
  <div id="observablehq-map-world-zoomable" class="observable-map"></div>
</div>
:::


:::{.light-bg}

## Sources

### Acknowledgements & previous work

- The initial version of the cartograms (world and separate cartograms for each continent) were created using R and ggplot2 during the #30DayChartChallenge in November 2023. The code and the maps can be found in the Github repository for the challenge: [https://github.com/bydata/30DayMapChallenge-2023](https://github.com/bydata/30DayMapChallenge-2023)
- The cartograms are based on the Observable notebook [Population Flags by Ansgar Wolsing](https://observablehq.com/@ansgar-wolsing/population-flags).
- Scrollytelling features supported by the [Closeread Quarto extension](https://closeread.netlify.app/).

### Data 

-   Country geometries: GISCO, Natural Earth.
-   Population: Worldbank, 2021 (via [{{gt}} R package](https://gt.rstudio.com/))
-   Flags: [HatScripts Circle Flags](https://github.com/HatScripts/circle-flags)

<div class="byline">
  <p>By: Ansgar Wolsing | 2023-2024 | 
  <a href="https://github.com/bydata/population-flags" target="_blank">
    <i class="fab fa-github"></i> GitHub Repository
  </a>
  </p>
</div>

:::